goog.addDependency('../../../../src/ime/background.js', ['goog.ime.chrome.os.Background'], ['goog.debug.ErrorHandler', 'goog.events.EventLike', 'goog.events.EventWrapper', 'goog.events.EventWrapper', 'goog.ime.chrome.os.Controller', 'goog.ime.chrome.os.LocalStorageHandlerFactory']);
goog.addDependency('../../../../src/ime/candidate.js', ['goog.ime.chrome.os.Candidate'], []);
goog.addDependency('../../../../src/ime/chineseconfig.js', ['goog.ime.chrome.os.ChineseConfig'], ['goog.ime.chrome.os.Config', 'goog.ime.chrome.os.Key', 'goog.ime.chrome.os.Modifier', 'goog.ime.chrome.os.State', 'goog.ime.chrome.os.StateID']);
goog.addDependency('../../../../src/ime/common.js', ['goog.ime.chrome.os.EventType', 'goog.ime.chrome.os.Key', 'goog.ime.chrome.os.KeyboardLayouts', 'goog.ime.chrome.os.MessageKey', 'goog.ime.chrome.os.Modifier', 'goog.ime.chrome.os.StateID', 'goog.ime.chrome.os.Status', 'goog.ime.chrome.os.TransID'], []);
goog.addDependency('../../../../src/ime/config.js', ['goog.ime.chrome.os.Config'], ['goog.ime.chrome.os.KeyboardLayouts']);
goog.addDependency('../../../../src/ime/configfactory.js', ['goog.ime.chrome.os.ConfigFactory'], ['goog.ime.chrome.os.Config', 'goog.ime.chrome.os.FlypyParser', 'goog.ime.chrome.os.PinyinConfig', 'goog.ime.offline.InputToolCode', 'goog.ime.offline.ShuangpinCode', 'goog.object'], {'lang': 'es6'});
goog.addDependency('../../../../src/ime/controller.js', ['goog.ime.chrome.os.Controller'], ['goog.Disposable', 'goog.events.EventHandler', 'goog.ime.chrome.os.ConfigFactory', 'goog.ime.chrome.os.EventType', 'goog.ime.chrome.os.Key', 'goog.ime.chrome.os.KeyboardLayouts', 'goog.ime.chrome.os.Model', 'goog.ime.chrome.os.Modifier', 'goog.ime.chrome.os.StateID', 'goog.ime.chrome.os.Status', 'goog.ime.chrome.os.View'], {'lang': 'es6'});
goog.addDependency('../../../../src/ime/decoder/candidate.js', ['goog.ime.offline.Candidate'], []);
goog.addDependency('../../../../src/ime/decoder/dataloader.js', ['goog.ime.offline.DataLoader'], ['goog.Disposable', 'goog.ime.offline.InputToolCode']);
goog.addDependency('../../../../src/ime/decoder/dataparser.js', ['goog.ime.offline.DataParser', 'goog.ime.offline.Long', 'goog.ime.offline.Target'], ['goog.array', 'goog.object']);
goog.addDependency('../../../../src/ime/decoder/decoder.js', ['goog.ime.offline.Decoder', 'goog.ime.offline.Response'], ['goog.Disposable', 'goog.array', 'goog.events.EventHandler', 'goog.ime.offline.Candidate', 'goog.ime.offline.DataLoader', 'goog.ime.offline.EventType', 'goog.ime.offline.MLDecoder', 'goog.ime.offline.TokenDecoder', 'goog.ime.offline.UserDecoder'], {'lang': 'es6'});
goog.addDependency('../../../../src/ime/decoder/eventtype.js', ['goog.ime.offline.EventType'], []);
goog.addDependency('../../../../src/ime/decoder/heap.js', ['goog.ime.offline.Heap'], ['goog.array', 'goog.object', 'goog.structs.Node']);
goog.addDependency('../../../../src/ime/decoder/inputtoolcode.js', ['goog.ime.offline.InputToolCode'], []);
goog.addDependency('../../../../src/ime/decoder/mldecoder.js', ['goog.ime.offline.MLDecoder'], ['goog.ime.offline.Candidate', 'goog.ime.offline.DataLoader', 'goog.ime.offline.DataParser', 'goog.ime.offline.Heap']);
goog.addDependency('../../../../src/ime/decoder/shuangpincode.js', ['goog.ime.offline.ShuangpinCode'], []);
goog.addDependency('../../../../src/ime/decoder/tokendecoder.js', ['goog.ime.offline.LatticeNode', 'goog.ime.offline.TokenDecoder', 'goog.ime.offline.TokenPath'], ['goog.array', 'goog.events.EventTarget', 'goog.ime.offline.DataLoader', 'goog.ime.offline.EventType']);
goog.addDependency('../../../../src/ime/decoder/userdecoder.js', ['goog.ime.offline.UserDecoder'], ['goog.ime.offline.Heap', 'goog.object']);
goog.addDependency('../../../../src/ime/localstoragehandler.js', ['goog.ime.chrome.os.LocalStorageHandler'], []);
goog.addDependency('../../../../src/ime/localstoragehandlerfactory.js', ['goog.ime.chrome.os.LocalStorageHandlerFactory'], ['goog.ime.chrome.os.PinyinLocalStorageHandler', 'goog.ime.offline.InputToolCode', 'goog.object']);
goog.addDependency('../../../../src/ime/model.js', ['goog.ime.chrome.os.Model'], ['goog.events.EventTarget', 'goog.ime.chrome.os.Candidate', 'goog.ime.chrome.os.ConfigFactory', 'goog.ime.chrome.os.EventType', 'goog.ime.chrome.os.Status', 'goog.ime.offline.Decoder']);
goog.addDependency('../../../../src/ime/parser.js', ['goog.ime.chrome.os.Parser'], [], {'lang': 'es5'});
goog.addDependency('../../../../src/ime/pinyinconfig.js', ['goog.ime.chrome.os.PinyinConfig'], ['goog.ime.chrome.os.ChineseConfig']);
goog.addDependency('../../../../src/ime/pinyinlocalstoragehandler.js', ['goog.ime.chrome.os.PinyinLocalStorageHandler'], ['goog.ime.chrome.os.LocalStorageHandler', 'goog.ime.offline.InputToolCode']);
goog.addDependency('../../../../src/ime/pinyinoption.js', ['goog.ime.chrome.os.PinyinOption'], ['goog.Disposable', 'goog.debug.ErrorHandler', 'goog.dom', 'goog.dom.TagName', 'goog.events', 'goog.events.EventHandler', 'goog.events.EventLike', 'goog.events.EventTarget', 'goog.events.EventType', 'goog.events.EventWrapper', 'goog.ime.chrome.os.LocalStorageHandlerFactory', 'goog.ime.offline.InputToolCode', 'goog.object']);
goog.addDependency('../../../../src/ime/state.js', ['goog.ime.chrome.os.State'], []);
goog.addDependency('../../../../src/ime/view.js', ['goog.ime.chrome.os.View'], ['goog.ime.chrome.os.ConfigFactory']);

