const FLYPY = {
    keymapping: {
        q: ['iu'],
        w: ['ei'],
        e: ['e'],
        r: ['r', 'uan', 'van'],
        t: ['ue', 've'],
        y: ['un', 'vn'],
        u: ['u'],
        i: ['i'],
        o: ['uo', 'o'],
        p: ['ie'],
        a: ['a'],
        s: ['ong', 'iong'],
        d: ['ai'],
        f: ['en'],
        g: ['eng'],
        h: ['ang'],
        j: ['an'],
        k: ['uai', 'ing'],
        l: ['uang', 'iang'],
        z: ['ou'],
        x: ['ua', 'ia'],
        c: ['ao'],
        v: ['ui', 'v'],
        b: ['in'],
        n: ['iao', 'n'],
        m: ['ian']
    },
    cartesian: (...a) => a.length === 1 ? a : a.reduce((a, b) => a.flatMap(d => b.map(e => [d, e].flat()))),
    zcsh: {
        u: 'sh',
        i: 'ch',
        v: 'zh'
    },
    aeo: new Set(['aa', 'ee', 'oo', 'aang', 'eeng',]),
    allowPinyin: new Set(["a",
        "ai",
        "an",
        "ang",
        "ao",
        "ba",
        "bai",
        "ban",
        "bang",
        "bao",
        "bei",
        "ben",
        "beng",
        "bi",
        "bian",
        "biao",
        "bie",
        "bin",
        "bing",
        "bo",
        "bu",
        "ca",
        "cai",
        "can",
        "cang",
        "cao",
        "ce",
        "cen",
        "ceng",
        "cha",
        "chai",
        "chan",
        "chang",
        "chao",
        "che",
        "chen",
        "cheng",
        "chi",
        "chong",
        "chou",
        "chu",
        "chua",
        "chuai",
        "chuan",
        "chuang",
        "chui",
        "chun",
        "chuo",
        "ci",
        "cong",
        "cou",
        "cu",
        "cuan",
        "cui",
        "cun",
        "cuo",
        "da",
        "dai",
        "dan",
        "dang",
        "dao",
        "de",
        "dei",
        "den",
        "deng",
        "di",
        "dia",
        "dian",
        "diao",
        "die",
        "ding",
        "diu",
        "dong",
        "dou",
        "du",
        "duan",
        "dui",
        "dun",
        "duo",
        "e",
        "ei",
        "en",
        "er",
        "fa",
        "fan",
        "fang",
        "fei",
        "fen",
        "feng",
        "fiao",
        "fo",
        "fou",
        "fu",
        "ga",
        "gai",
        "gan",
        "gang",
        "gao",
        "ge",
        "gei",
        "gen",
        "geng",
        "gong",
        "gou",
        "gu",
        "gua",
        "guai",
        "guan",
        "guang",
        "gui",
        "gun",
        "guo",
        "ha",
        "hai",
        "han",
        "hang",
        "hao",
        "he",
        "hei",
        "hen",
        "heng",
        "hong",
        "hou",
        "hu",
        "hua",
        "huai",
        "huan",
        "huang",
        "hui",
        "hun",
        "huo",
        "ji",
        "jia",
        "jian",
        "jiang",
        "jiao",
        "jie",
        "jin",
        "jing",
        "jiong",
        "jiu",
        "ju",
        "juan",
        "jue",
        "jun",
        "jve",
        "ka",
        "kai",
        "kan",
        "kang",
        "kao",
        "ke",
        "kei",
        "ken",
        "keng",
        "kong",
        "kou",
        "ku",
        "kua",
        "kuai",
        "kuan",
        "kuang",
        "kui",
        "kun",
        "kuo",
        "la",
        "lai",
        "lan",
        "lang",
        "lao",
        "le",
        "lei",
        "leng",
        "li",
        "lia",
        "lian",
        "liang",
        "liao",
        "lie",
        "lin",
        "ling",
        "liu",
        "lo",
        "long",
        "lou",
        "lu",
        "luan",
        "lue",
        "lun",
        "luo",
        "lv",
        "lve",
        "ma",
        "mai",
        "man",
        "mang",
        "mao",
        "me",
        "mei",
        "men",
        "meng",
        "mi",
        "mian",
        "miao",
        "mie",
        "min",
        "ming",
        "miu",
        "mo",
        "mou",
        "mu",
        "na",
        "nai",
        "nan",
        "nang",
        "nao",
        "ne",
        "nei",
        "nen",
        "neng",
        "ni",
        "nian",
        "niang",
        "niao",
        "nie",
        "nin",
        "ning",
        "niu",
        "nong",
        "nou",
        "nu",
        "nuan",
        "nue",
        "nun",
        "nuo",
        "nv",
        "nve",
        "o",
        "ou",
        "pa",
        "pai",
        "pan",
        "pang",
        "pao",
        "pei",
        "pen",
        "peng",
        "pi",
        "pian",
        "piao",
        "pie",
        "pin",
        "ping",
        "po",
        "pou",
        "pu",
        "qi",
        "qia",
        "qian",
        "qiang",
        "qiao",
        "qie",
        "qin",
        "qing",
        "qiong",
        "qiu",
        "qu",
        "quan",
        "que",
        "qun",
        "qve",
        "ran",
        "rang",
        "rao",
        "re",
        "ren",
        "reng",
        "ri",
        "rong",
        "rou",
        "ru",
        "ruan",
        "rui",
        "run",
        "ruo",
        "sa",
        "sai",
        "san",
        "sang",
        "sao",
        "se",
        "sen",
        "seng",
        "sha",
        "shai",
        "shan",
        "shang",
        "shao",
        "she",
        "shei",
        "shen",
        "sheng",
        "shi",
        "shou",
        "shu",
        "shua",
        "shuai",
        "shuan",
        "shuang",
        "shui",
        "shun",
        "shuo",
        "si",
        "song",
        "sou",
        "su",
        "suan",
        "sui",
        "sun",
        "suo",
        "ta",
        "tai",
        "tan",
        "tang",
        "tao",
        "te",
        "teng",
        "ti",
        "tian",
        "tiao",
        "tie",
        "ting",
        "tong",
        "tou",
        "tu",
        "tuan",
        "tui",
        "tun",
        "tuo",
        "wa",
        "wai",
        "wan",
        "wang",
        "wei",
        "wen",
        "weng",
        "wo",
        "wu",
        "xi",
        "xia",
        "xian",
        "xiang",
        "xiao",
        "xie",
        "xin",
        "xing",
        "xiong",
        "xiu",
        "xu",
        "xuan",
        "xue",
        "xun",
        "xve",
        "ya",
        "yan",
        "yang",
        "yao",
        "ye",
        "yi",
        "yin",
        "ying",
        "yo",
        "yong",
        "you",
        "yu",
        "yuan",
        "yue",
        "yun",
        "yve",
        "za",
        "zai",
        "zan",
        "zang",
        "zao",
        "ze",
        "zei",
        "zen",
        "zeng",
        "zha",
        "zhai",
        "zhan",
        "zhang",
        "zhao",
        "zhe",
        "zhei",
        "zhen",
        "zheng",
        "zhi",
        "zhong",
        "zhou",
        "zhu",
        "zhua",
        "zhuai",
        "zhuan",
        "zhuang",
        "zhui",
        "zhun",
        "zhuo",
        "zi",
        "zong",
        "zou",
        "zu",
        "zuan",
        "zui",
        "zun",
        "zuo",]),
    parse: (sentence) => {
        if (!sentence) return null
        const result = Array.from(sentence).reduce((prev, curr, idx) => {
            if (prev.last === "'") {
                if (curr === "'") {

                    return prev
                }
                prev.cut += curr
                if (this.zcsh[curr]) {
                    curr = this.zcsh[curr]
                }
                prev.trans.push([curr])
                prev.last = curr
            } else {
                let tarray = []
                if (!this.keymapping[curr]) {
                    if (curr === "'") {
                        prev.trans.push([curr])
                        prev.last = curr
                        prev.cut += `${curr}`
                    } else {
                        prev.trans.push(["'"])
                        prev.trans.push([curr])
                        prev.trans.push(["'"])
                        prev.last = "'"
                        prev.cut += `'${curr}'`
                    }
                    return prev
                }
                for (const vowel of this.keymapping[curr]) {
                    if (this.allowPinyin.has(prev.last + vowel)) {
                        tarray.push(vowel)
                    } else if (this.aeo.has(prev.last + vowel)) {
                        if (vowel.length === 1) {
                            tarray.push('')
                        } else {
                            tarray.push(vowel.slice(1))
                        }

                    }
                }
                if (tarray.length === 0) {
                    prev.trans.push(["'"])
                    prev.trans.push([curr])
                    prev.last = curr
                    prev.cut += `'${curr}`
                } else {
                    prev.trans.push(tarray)
                    prev.trans.push(["'"])
                    prev.cut += `${curr}'`
                    prev.last = "'"
                }
            }
            return prev;
        }, {cut: '', trans: [], last: "'"})
        const trans = this.cartesian(...result.trans).map(arr => arr.join(''))
        if (trans.length===0) {
            return sentence
        }
        return trans[0]

    }
}
for(const k in FLYPY){
   this[k]=FLYPY[k]
}
console.log(FLYPY.parse('ul'));